AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - setup.rb
    - 'tmp/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/*.rake'
    - 'spec/client_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Rails:
  Enabled: true

Rails/Date:
  Severity: error

Rails/TimeZone:
  Severity: error

Style/IndentationWidth:
  Severity: error

Style/IndentationConsistency:
  Severity: error

Style/IndentHash:
  EnforcedStyle: consistent
  Severity: error

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  Severity: error

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Severity: warning

Metrics/CyclomaticComplexity:
  Severity: warning

Metrics/MethodLength:
  Max: 40

Style/SignalException:
  EnforcedStyle: only_raise

Style/DotPosition:
  EnforcedStyle: trailing

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAroundOperators:
  Enabled: true

Style/SpaceBeforeSemicolon:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true
  AllowDSLWriters: true

Style/CaseIndentation:
  Enabled: true
  IndentOneStep: false
  EnforcedStyle: case

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/IndentArray:
  EnforcedStyle: consistent

Style/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/LineEndConcatenation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ClassMethods:
  Enabled: false

Style/SpaceAfterMethodName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/BlockEndNewline:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/PredicateName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Rails/Validation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Lint/FormatParameterMismatch:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/MutableConstant:
  Enabled: false
